idle_bg = "#2e344000" # nord0
idle_fg = "#81a1c100" # light blue
info_bg = "#5e81ac00" # dark blue
info_fg = "#2e344000" # nord0
good_bg = "#a3be8600" # green
good_fg = "#2e344000" # nord0
warning_bg = "#ebcb8b00" # yellow
warning_fg = "#2e344000" # nord0
critical_bg = "#bf616a00" # red
critical_fg = "#2e344000" # nord0
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
